### ISSUE TITLE
PropertyAdmin: NullPointerException

### ISSUE THREAD

**Issue by wutz10** [denkunddachte-agaffke/B2BiUtils#16]
129 ✖  KX_KEYGEN_GRACE_PERIOD         30                                                 2023-05-16 10:37:23 izse364                                      
Exception in thread "main" java.lang.NullPointerException
        at de.denkunddachte.utils.WordUtil.wrap(WordUtil.java:171)
        at de.denkunddachte.utils.WordUtil.wrap(WordUtil.java:162)
        at de.denkunddachte.b2biutil.api.PropertiesManager.listProperties(PropertiesManager.java:179)
        at de.denkunddachte.b2biutil.api.PropertiesManager.main(PropertiesManager.java:114)

**Comment by wutz10** [comment]
Probably: on 
<hmtl><pre>
Dear team,

a new SSH public key for user ${KX_LOCAL_USER} was created on ${AZ_CSLM_SOURCE}. The key can be fetched with SFTP from:

${KX_SHARE_HOST}${KX_SHARE_MBX_AGL}/${KEY_NAME}.pub

Please activate the new key within ${KX_KEYGEN_GRACE_PERIOD} days on all participating servers (see attached list).

Best regards,
${AZ_CSLM_SOURCE}
</pre></html>
